//-----------------------------------------------------------------------------
//! Type definitions and data structures for AI Assistant
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
//! Represents a request to the AI system
class AIRequest
{
	AIRequestType type;
	string userInput;
	WorkbenchContext context;
	int timestamp;
	string response;
	bool isCompleted;
	string errorMessage;
	
	void AIRequest()
	{
		isCompleted = false;
		response = "";
		errorMessage = "";
	}
}

//-----------------------------------------------------------------------------
//! Base callback interface for AI responses
class AIResponseCallback
{
	void OnSuccess(string response)
	{
		// Override in derived classes
	}
	
	void OnError(string error)
	{
		// Override in derived classes
	}
}

//-----------------------------------------------------------------------------
//! Service-level callback for AI API communication
class AIServiceCallback
{
	void OnSuccess(string response)
	{
		// Override in derived classes
	}
	
	void OnError(string error)
	{
		// Override in derived classes
	}
}

//-----------------------------------------------------------------------------
//! Code generation callback
class AICodeGenerationCallback : AIServiceCallback
{
	protected AIResponseCallback m_UserCallback;
	
	void AICodeGenerationCallback(AIResponseCallback userCallback)
	{
		m_UserCallback = userCallback;
	}
	
	override void OnSuccess(string response)
	{
		// Process code generation response
		string processedCode = ProcessGeneratedCode(response);
		m_UserCallback.OnSuccess(processedCode);
	}
	
	override void OnError(string error)
	{
		m_UserCallback.OnError("Code generation failed: " + error);
	}
	
	protected string ProcessGeneratedCode(string rawResponse)
	{
		// Clean up and validate generated code
		string cleanedCode = rawResponse;
		
		// Remove any markdown formatting
		cleanedCode = cleanedCode.Replace("```cpp", "");
		cleanedCode = cleanedCode.Replace("```c", "");
		cleanedCode = cleanedCode.Replace("```", "");
		
		// Add standard header if missing
		if (!cleanedCode.Contains("//"))
		{
			string header = "//-----------------------------------------------------------------------------\n";
			header += "//! AI Generated Code\n";
			header += "//! Generated on: " + GetCurrentTimeString() + "\n";
			header += "//-----------------------------------------------------------------------------\n\n";
			cleanedCode = header + cleanedCode;
		}
		
		return cleanedCode;
	}
	
	protected string GetCurrentTimeString()
	{
		// Simple timestamp - could be enhanced with proper date/time formatting
		return System.GetTickCount().ToString();
	}
}

//-----------------------------------------------------------------------------
//! Code analysis callback
class AICodeAnalysisCallback : AIServiceCallback
{
	protected AIResponseCallback m_UserCallback;
	
	void AICodeAnalysisCallback(AIResponseCallback userCallback)
	{
		m_UserCallback = userCallback;
	}
	
	override void OnSuccess(string response)
	{
		string analysisReport = FormatAnalysisReport(response);
		m_UserCallback.OnSuccess(analysisReport);
	}
	
	override void OnError(string error)
	{
		m_UserCallback.OnError("Code analysis failed: " + error);
	}
	
	protected string FormatAnalysisReport(string rawAnalysis)
	{
		string formattedReport = "//=============================================================================\n";
		formattedReport += "//! CODE ANALYSIS REPORT\n";
		formattedReport += "//! Generated by AI Assistant\n";
		formattedReport += "//=============================================================================\n\n";
		formattedReport += rawAnalysis;
		
		return formattedReport;
	}
}

//-----------------------------------------------------------------------------
//! Debugging assistance callback
class AIDebuggingCallback : AIServiceCallback
{
	protected AIResponseCallback m_UserCallback;
	
	void AIDebuggingCallback(AIResponseCallback userCallback)
	{
		m_UserCallback = userCallback;
	}
	
	override void OnSuccess(string response)
	{
		string debugReport = FormatDebugReport(response);
		m_UserCallback.OnSuccess(debugReport);
	}
	
	override void OnError(string error)
	{
		m_UserCallback.OnError("Debugging assistance failed: " + error);
	}
	
	protected string FormatDebugReport(string rawResponse)
	{
		string debugReport = "//=============================================================================\n";
		debugReport += "//! DEBUGGING ASSISTANCE\n";
		debugReport += "//! AI-powered debug analysis\n";
		debugReport += "//=============================================================================\n\n";
		debugReport += rawResponse;
		
		// Could add more sophisticated formatting here
		return debugReport;
	}
}

//-----------------------------------------------------------------------------
//! Documentation generation callback
class AIDocumentationCallback : AIServiceCallback
{
	protected AIResponseCallback m_UserCallback;
	
	void AIDocumentationCallback(AIResponseCallback userCallback)
	{
		m_UserCallback = userCallback;
	}
	
	override void OnSuccess(string response)
	{
		string documentation = FormatDocumentation(response);
		m_UserCallback.OnSuccess(documentation);
	}
	
	override void OnError(string error)
	{
		m_UserCallback.OnError("Documentation generation failed: " + error);
	}
	
	protected string FormatDocumentation(string rawDocs)
	{
		// Format as proper code comments
		string documentation = "//-----------------------------------------------------------------------------\n";
		documentation += "//! AUTO-GENERATED DOCUMENTATION\n";
		documentation += "//-----------------------------------------------------------------------------\n";
		
		// Split response into lines and format as comments
		array<string> lines = {};
		rawDocs.Split("\n", lines);
		
		foreach (string line : lines)
		{
			if (!line.IsEmpty())
			{
				documentation += "//! " + line + "\n";
			}
			else
			{
				documentation += "//!\n";
			}
		}
		
		return documentation;
	}
}

//-----------------------------------------------------------------------------
//! Optimization suggestions callback
class AIOptimizationCallback : AIServiceCallback
{
	protected AIResponseCallback m_UserCallback;
	
	void AIOptimizationCallback(AIResponseCallback userCallback)
	{
		m_UserCallback = userCallback;
	}
	
	override void OnSuccess(string response)
	{
		string optimizationReport = FormatOptimizationReport(response);
		m_UserCallback.OnSuccess(optimizationReport);
	}
	
	override void OnError(string error)
	{
		m_UserCallback.OnError("Optimization analysis failed: " + error);
	}
	
	protected string FormatOptimizationReport(string rawResponse)
	{
		string report = "//=============================================================================\n";
		report += "//! OPTIMIZATION SUGGESTIONS\n";
		report += "//! Performance improvement recommendations\n";
		report += "//=============================================================================\n\n";
		report += rawResponse;
		
		return report;
	}
}

//-----------------------------------------------------------------------------
//! Code explanation callback
class AIExplanationCallback : AIServiceCallback
{
	protected AIResponseCallback m_UserCallback;
	
	void AIExplanationCallback(AIResponseCallback userCallback)
	{
		m_UserCallback = userCallback;
	}
	
	override void OnSuccess(string response)
	{
		string explanation = FormatExplanation(response);
		m_UserCallback.OnSuccess(explanation);
	}
	
	override void OnError(string error)
	{
		m_UserCallback.OnError("Code explanation failed: " + error);
	}
	
	protected string FormatExplanation(string rawResponse)
	{
		string explanation = "//=============================================================================\n";
		explanation += "//! CODE EXPLANATION\n";
		explanation += "//! AI-powered code analysis and explanation\n";
		explanation += "//=============================================================================\n\n";
		explanation += rawResponse;
		
		return explanation;
	}
}

//-----------------------------------------------------------------------------
//! Refactoring assistance callback
class AIRefactoringCallback : AIServiceCallback
{
	protected AIResponseCallback m_UserCallback;
	
	void AIRefactoringCallback(AIResponseCallback userCallback)
	{
		m_UserCallback = userCallback;
	}
	
	override void OnSuccess(string response)
	{
		string refactoredCode = ProcessRefactoredCode(response);
		m_UserCallback.OnSuccess(refactoredCode);
	}
	
	override void OnError(string error)
	{
		m_UserCallback.OnError("Code refactoring failed: " + error);
	}
	
	protected string ProcessRefactoredCode(string rawResponse)
	{
		string refactoredCode = "//-----------------------------------------------------------------------------\n";
		refactoredCode += "//! REFACTORED CODE\n";
		refactoredCode += "//! AI-assisted code refactoring\n";
		refactoredCode += "//-----------------------------------------------------------------------------\n\n";
		
		// Clean up response similar to code generation
		string cleanedCode = rawResponse;
		cleanedCode = cleanedCode.Replace("```cpp", "");
		cleanedCode = cleanedCode.Replace("```c", "");
		cleanedCode = cleanedCode.Replace("```", "");
		
		refactoredCode += cleanedCode;
		
		return refactoredCode;
	}
}